### ISSUE TITLE
IDC and reference data handling

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-au/elixir-biocommons-colab#10]
* do we need a UI here to actually list and show the deployed reference data sets
* get a kickstart int IDC
* discuss how to contribute to IDC

**Comment by bgruening** [comment]
@cat-bro, @natefoo, @afgane, @nuwang

**Comment by AnnaSyme** [comment]
adding myself

**Comment by hechth** [comment]
@hechth

**Comment by jlqfab** [comment]
@jlqfab

**Comment by itisAliRH** [comment]
@itisAliRH

**Comment by jlqfab** [comment]
@jlqfab

**Comment by bgruening** [comment]
Thanks for the great discussion. Please join the IDC channel to get more information in the future: https://matrix.to/#/#galaxyproject_idc:gitter.im
