### ISSUE TITLE
Galaxy federated identity demo & discussion

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-au/elixir-biocommons-colab#13]
Very nice presentation of the Biocommons about recent developments and plans of Galaxy federated identity.

* [x] create a main Galaxy issues and then smaller issues to break work apart (@nuwang)

**Comment by bgruening** [comment]
ping @uwwint

**Comment by bgruening** [comment]
I think this can be closed when the upstream issues have been created.

**Comment by uwwint** [comment]
Onboarding @nuwang

**Comment by nuwang** [comment]
Closed by: https://github.com/galaxyproject/galaxy/issues/16545
