### ISSUE TITLE
metabolomics & proteomics tools harmonization

### ISSUE THREAD

**Issue by hechth** [usegalaxy-au/elixir-biocommons-colab#14]
lets outline a set of common tools to have on usegalaxy.eu and usegalaxy.org.au and an overview of which trainings are supported with this, and then get all the common tools on the instances and ideally auto-updated.

**Comment by hechth** [comment]
@neoformit @bgruening @supernord @cat-bro

**Comment by supernord** [comment]
Thanks @hechth 😄 
I'm working on a script that will let us query the GTN API and extract the proteomics/metabolomics tools that are represented there, which was first on the criteria list we started last week:

- Tool is in a GTN tutorial
- Tool is in a IWC workflow
- Tool is known to be actively maintained
- Tool is prioritised by a regional community

**Comment by hechth** [comment]
I already asked if someone has a script to get which trainings are available on which instances, so maybe we could first create these monitor scripts and have some github repo to display tool and training availability?

**Comment by supernord** [comment]
Agree, I was intending to also extend this to the second and fourth points by also querying:
- IWC workflows via WorkflowHub entries https://workflowhub.eu/projects/33/workflows
- actual tools available by instance (starting with EU and AU)

What do you think?

**Comment by hechth** [comment]
https://github.com/usegalaxy-au/usegalaxy-au-tools/pull/951#pullrequestreview-1536273838

**Comment by bgruening** [comment]
@supernord https://ephemeris.readthedocs.io/en/latest/commands/workflow-to-tools.html assuming that every tutorial as a workflow, which it should.

**Comment by hechth** [comment]
Initial discussion has been moved here: https://docs.google.com/document/d/1k3iRSNDUMeI3BNmN5BHP_E0K26o0jnbYvRv1ZzJRN8A/edit#heading=h.8jgdikdhmmc8

**Comment by supernord** [comment]
https://github.com/AustralianBioCommons/create-gtn-rocrates/blob/e9afc0b93493f491a99bfa8f776b76e6375547d1/gtn_tools.py
