### ISSUE TITLE
Templatable content for Galaxy

### ISSUE THREAD

**Issue by neoformit** [usegalaxy-au/elixir-biocommons-colab#15]
Like welcome.html, Galaxy AU would benefit from some more custom HTML templates for some Galaxy components, such as:

- footer.html

@bgruening

**Comment by bgruening** [comment]
Lets discuss this tomorrow?

**Comment by neoformit** [comment]
We can extend the existing plugin/webhooks feature to include new `type`s like "footer_login", "footer_new_user", "footer_tool" and implement footers and other templatable content as webhooks.

**Comment by bgruening** [comment]
Thanks for the discussions Cam!
