### ISSUE TITLE
Conda, Containers and Galaxy Tools discussions and updates

### ISSUE THREAD

**Issue by hechth** [usegalaxy-au/elixir-biocommons-colab#16]
Discussion with @mthang and @neoformit about recent Conda, Containers and Galaxy tools development.

We talked about https://pubmed.ncbi.nlm.nih.gov/36828587/ and the bots that helps our community to build new tools.

Also important is the https://github.com/galaxyproject/galaxy-language-server

**Comment by hechth** [comment]
environment variables by default defined by conda: https://docs.conda.io/projects/conda-build/en/stable/user-guide/environment-variables.html

conda-forge: overall recommended, but stricter review process and also support for windows etc. https://conda-forge.org/docs/maintainer/adding_pkgs.html

**Comment by hechth** [comment]
mulled package container build: https://github.com/BioContainers/multi-package-containers

What happens if you have a single package dependency that is conda-forge? There is no prebuilt container.

**Comment by hechth** [comment]
planemo-monitor repo: https://github.com/galaxyproject/planemo-monitor

Has list of repositories that are registered to auto-create mulled containers with planemo which posts up the pull requests to the multi-package-container repository

**Comment by hechth** [comment]
CRON job to check docker containers on quay.io in this repo to auto build singularity images: https://github.com/BioContainers/singularity-build-bot

All bot magic is depicted here:

![grafik](https://github.com/usegalaxy-au/elixir-biocommons-colab/assets/469983/c035fe0b-db1b-4ae4-bb87-d97f9af0d774)

Paper is here: [10.1101/gr.276963.122 ](https://genome.cshlp.org/content/33/2/261)

**Comment by hechth** [comment]
galaxy tool testing logic: https://github.com/galaxyproject/galaxy/tree/dev/lib/galaxy/tool_util/verify/asserts

**Comment by hechth** [comment]
Macros can be parameterized https://planemo.readthedocs.io/en/latest/writing_advanced.html#macros-reusable-elements

**Comment by hechth** [comment]
planemo documentation contains information on which objects and which parameters on the variables in the cheetah template exist

**Comment by hechth** [comment]
the ultimate truth: https://github.com/galaxyproject/galaxy/blob/master/lib/galaxy/tool_util/xsd/galaxy.xsd

**Comment by hechth** [comment]
interactive tools example: https://github.com/bgruening/docker-odv/blob/main/Dockerfile

**Comment by bgruening** [comment]
We extended this session with a live review session of Bioconda recipes, multi-tool-container contributions.

**Comment by hechth** [comment]
* Extras -> add Galaxy tool, bio.tools identifier and DOI to packages that have papers
o see deeptools example
* https://github.com/research-software-ecosystem/content
* How does the bash build file work?
o example: https://github.com/bioconda/bioconda-recipes/pull/42144/files
o tool was skip listed, so build-fail-blacklist is the file containing that info
* Check if SPDX identifiers are correct
* Check if python versions between host and build are consistent
* pure python package should be noarch: python
* use matplotlib-base if possible
* host vs. run vs. build environment
o R host and run need to be the same
o host is independent from the platform, build might change and is platform specific, so needs to be adapted for cross compiling
* Usually doesn't have to up-to-date with master -> only if really outdated
* script section in meta.yaml file replaces build.sh script
* entry_point can be specified in the meta.yaml but is better if done on the package layer
* noarch: generic -> everything that is noarch: python I guess
* patches can be applied to fix something
o https://github.com/bioconda/bioconda-recipes/pull/42140
o patch example: https://github.com/bioconda/bioconda-recipes/blob/f675a72becc5f05b1e331fc6dbc2cfac4e67c3b2/recipes/ncbi-genome-download/assembly_accession.patch
o patches can be created with diff
o pacthes in bioconda also need a build number bump
* use comments to justify pins
* javascript packages need npm as dependency and need to be in npm
* julia package server is also included in conda deps and grayskull utility
