### ISSUE TITLE
Help Desk discussion and how do we run user-support

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-au/elixir-biocommons-colab#19]
@gallardoalba let me know if you are interested in this discussion.

**Comment by bgruening** [comment]
Bjoern wants to especially talk about a potential gitlab-based error reporting.

**Comment by sanjaysrikakulam** [comment]
For incidents and ticketing, I would suggest using a proper ticket system service. For example something like [RT](https://bestpractical.com/request-tracker). It is free if you would like to host it yourself and one can get community support for issues.

**Comment by mira-miracoli** [comment]
The advantage of GitLab would be that it already exists in our university

**Comment by paulzierep** [comment]
I like the idea, would make the discussion for specific tools more seamlessly.

**Comment by GarethPrice-Aus** [comment]
GA uses Freshdesk. This is commercial and provided to us by one of our funders (ARDC) who pay for the licencing (per person). We have 9 people on our account. This system provides us with a Dashboard related to ticket activity (time to respond, open/closed, etc). We find this useful information for our funders. Each ticket triggers a small user satisfaction survey which is also very useful.
The majority of tickets are quota access, tool access and science questions. A smaller percentage is about tools erroring.

**Comment by hechth** [comment]
I'd also be interested in this, as we are currently setting up a helpdesk internally for our application support with GitLab (non Galaxy related stuff and IT services) - would be nice if something similar could be done for Galaxy.

**Comment by bgruening** [comment]
* AU is using freshdesk, commercial service
* using it for user satisfaction measures 
  * survey is sent when ticket is closed
* data privacy?
* How do we integrate it with sentry, github issues etc ...
