### ISSUE TITLE
add funders/grant information to the tool schema and tool form

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-au/elixir-biocommons-colab#2]
* [x] schema.org/Grant can be added to https://docs.galaxyproject.org/en/latest/dev/schema.html (planemo + backend?)
* [ ] Backend work
  * [ ] Add `Grant` field to planemo linting in `lib/galaxy/tool_util/linters/xml_order.py` (planemo)
  * [x] add parsing logic to the backend
  * [ ] add tests for the backend
* [ ] Grant information should be displayed in the tool form in `client/src/components/Tool/ToolFooter.vue` (Front end)
  * [x] Create a `Funding.vue` component in `client/src/components/SchemaOrg`
  * [x] Create a `GrantViewer.vue` component in `client/src/components/SchemaOrg`
  * [x] Adapt `ToolFooter.vue` and `ToolCard.vue` to support the funding mechanism
  * [ ] Implement tests in `ToolFooter.test.js`
  * [ ] Implement tests in `ToolCard.test.js`
* [x] the tool form has currently a regression and does not show schema.org annotations at all

**Comment by bgruening** [comment]
ping @hechth

**Comment by hechth** [comment]
@bgruening please assign me, can't assign myself

**Comment by hechth** [comment]
@itisAliRH do you want to participate and support me in this?

**Comment by itisAliRH** [comment]
> @itisAliRH do you want to participate and support me in this?

@hechth of course✌️

**Comment by hechth** [comment]
@bgruening do all fields from schema.org have to be present in the `galaxy.xsd` schema?

**Comment by hechth** [comment]
@ElectronicBlueberry some code in the forms is repeated in all of them - can we share this template somehow between the compoenents to avoid a third copy and paste? 

https://github.com/galaxyproject/galaxy/blob/45e020e7603f4d0e96a2fe171ce1b3f01cfc6234/client/src/components/SchemaOrg/PersonForm.vue#L2-L22

**Comment by bgruening** [comment]
> @bgruening do all fields from schema.org have to be present in the `galaxy.xsd` schema?

I don't think so. We can start with a subset. But make sure we can implement other fields later without breaking any backward compatibility.

**Comment by hechth** [comment]
WIP is here: https://github.com/hechth/galaxy/tree/grant_tool_tag

**Comment by bgruening** [comment]
And here is the PR: https://github.com/galaxyproject/galaxy/pull/16477 :1st_place_medal:
