### ISSUE TITLE
Integrate a reference data page in Galaxy

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-au/elixir-biocommons-colab#20]
Out of the [Vue workshop](https://github.com/usegalaxy-au/elixir-biocommons-colab/issues/7) done by @ElectronicBlueberry a cool project originated, by @neoformit, to list all reference data available in a Galaxy server. 

Follow-up discussions and the PR can be found here: https://github.com/galaxyproject/galaxy/pull/16427

**Comment by neoformit** [comment]
We have a PR for this work now, but we should work towards a user-friendly UI which clearly communicates to users the relationship between dbkeys (reference subjects?), subject reference data and generic reference data. This requires a UI which allows users to search/filter subjects and tools (for which ref data exists) and the links between them.
