### ISSUE TITLE
subdomain / Galaxy labs discussion and deployment

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-au/elixir-biocommons-colab#3]
The idea here is to use the new integrated way to deploy subdomains and deprecated the hack that is EU doing.

* [x] tool box handling
* [x] CSS modifications

**Comment by bgruening** [comment]
ping @mira-miracoli, @afgane, @cat-bro, @AnnaSyme, @hechth

**Comment by cat-bro** [comment]
ping @neoformit

**Comment by hexylena** [comment]
I'll add myself here since I wrote the original role for it and have opinions on the replacement :) https://github.com/usegalaxy-eu/ansible-galaxy-subdomains

**Comment by ElectronicBlueberry** [comment]
I can help with the theming, if there's questions specific to that

**Comment by jlqfab** [comment]
Cam's going to loop me in on this (admin/backend aspects).

**Comment by mira-miracoli** [comment]
I am currently working on a new ansible role, but I am stuck with [the static directory per host part](https://github.com/galaxyproject/galaxy/pull/12379)

**Comment by hexylena** [comment]
feel free to update the existing role so we don't have this old deprecated
thing :)

**Comment by bgruening** [comment]
Can we do this Wednesday AU afternoon time? We could start at 16.00 with a simple, stupid introduction by me and later around 17.00 (9:00 European time) @mira-miracoli could join to talk about playbook.

Is that ok?

**Comment by neoformit** [comment]
Yep fine with me!

**Comment by bgruening** [comment]
Ansible playbook here: https://github.com/usegalaxy-eu/ansible-galaxy-subdomains

**Comment by bgruening** [comment]
Theming PR: https://galaxyproject.org/news/2023-04-25-themes-in-galaxy/

**Comment by bgruening** [comment]
Slides from Mira: https://docs.google.com/presentation/d/1N1u1b0AqJ-ZVz8qKO5YxkwUSjSR5HwnuSxTsj6wAevE/

**Comment by bgruening** [comment]
Thanks, Mira for guiding us through the ansible role and the new chances.

**Comment by hechth** [comment]
Is there a GTN course for how to deploy a subdomain using these new features?

**Comment by neoformit** [comment]
Not that I've seen, but it would be good to write up once the new Ansible role is available and working. Would you write a "how it works in Galaxy" followed by "How to deploy it with Ansible" as a single article?
