### ISSUE TITLE
enhanced data upload

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-au/elixir-biocommons-colab#4]
* [x] Discussion round
* rewrite of the data upload modal https://github.com/galaxyproject/galaxy/issues/16407
* how can a new upload story look like?
  * deeper integration into the activity bar
* uploading of more complex archives (zip, RO-Crate, local folders, DRS bundles, ...)
  * peak into such archives and let users choose what to extract, upload 

@neoformit did some initial scoping on this here: https://github.com/galaxyproject/galaxy/issues/15296

**Comment by bgruening** [comment]
@afgane, @cat-bro, @nuwang, @AnnaSyme, @electronicblueberry, @itisAliRH, @hechth, @guerler

**Comment by shiltemann** [comment]
@shiltemann might join too 👍

**Comment by pauldg** [comment]
@pauldg

**Comment by jlqfab** [comment]
@jlqfab

**Comment by pauldg** [comment]
Small amount of notes, please add anything I've missed:

- Upload functionality needs to be rewritten
	- Have two visually identical upload interfaces (beta version) for 1-2 release that would highlight regressions in features
- One basic upload functionality in the activity bar and a middle panel for more advanced upload
- Inspectable Zip upload with filtering and selection (drill down)
- Project "folders" or a collection of links in activity bar
	- pinboard?

**Comment by bgruening** [comment]
@neoformit do you have anything more to add?

**Comment by neoformit** [comment]
Proposed features:

**v1:**
- Client-side zip archive upload
- Drilldown component to inspect/select zip content
- Use existing upload API endpoint

**v2+:**
- Accept RO-crate spec, DRS and folder upload
- Backend web (URL) fetch (async; return archive tree to client, select, extract to datasets)
- Accept tar archives (backend and client?)
- Use of RANGE headers for partial web fetch of zip archives

**Comment by bgruening** [comment]
Thank everyone for the discussion. Can someone sum up this discussion please and put it into a proper Galaxy issue?

**Comment by neoformit** [comment]
Shall I just update my existing issue with our conclusions?

**Comment by bgruening** [comment]
Yes that would be nice. This one will be closed and upstream issues should be created.

**Comment by neoformit** [comment]
@bgruening have updated my tracking issue on galaxyproject :point_up: 
One point that stood out is that creating an "extract archive from history" feature would implicitly solve "extract remote archive" since the user could do a regular URL fetch and then select the archive from their history.

**Comment by bgruening** [comment]
This here is also merged: https://github.com/galaxyproject/galaxy/pull/16381 and could maybe be used?
