### ISSUE TITLE
VueJS workshop

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-au/elixir-biocommons-colab#7]
@electronicblueberry is offering a VueJS workshop and an introduction to the Galaxy client. We are aiming for two days.

**Comment by bgruening** [comment]
@electronicblueberry, @afgane, @cat-bro, @AnnaSyme, @hechth, @itisAliRH, @shiltemann

**Comment by hexylena** [comment]
@hexylena will join too :)

**Comment by ElectronicBlueberry** [comment]
Thursday and Friday this week

**Comment by nuwang** [comment]
@nuwang

**Comment by neoformit** [comment]
@neoformit

**Comment by pauldg** [comment]
@pauldg

**Comment by pauldg** [comment]
@ElectronicBlueberry what's the estimated schedule for each day? Just to be able to plan around

**Comment by ElectronicBlueberry** [comment]
@pauldg  https://docs.google.com/document/d/1Rch3MsxGFPxkpHKNzJQJQpIG5RNqa9RYdkcIzg0Z_Ws/edit?usp=sharing

**Comment by bgruening** [comment]
We had a great workshop. New frontend things are coming!
